export const projects = [
  {
    id: 1,
    title: "Tienda Virtual E-commerce",
    slug: "tienda-virtual",
    description: "Plataforma de comercio electrónico desarrollada con Vue.js y Laravel, ofreciendo una experiencia de compra fluida y moderna.",
    image: "/images/digital-wardrobe-transparent-screen.webp",
    technologies: ["Vue.js", "Laravel", "Tailwind CSS", "MySQL"],
    link: "https://github.com/MisterAlvaro/The_Boulevard",
  },
  {
    id: 2,
    title: "Marketing Agency Landing",
    slug: "marketing-agency",
    description: "Landing page moderna y atractiva para una agencia de marketing digital, con animaciones suaves y diseño responsivo.",
    image: "/images/map-lying-wooden-table.webp",
    technologies: ["Next.js", "Tailwind CSS", "Framer Motion"],
    link: "https://github.com/MisterAlvaro/BBKMarketingSolutions",
  },
  {
    id: 3,
    title: "EMPET",
    slug: "empet-landing",
    description: "Sitio web institucional para EMPET, sucursal de CUPET, con información de servicios y ubicaciones.",
    image: "/images/logo_cupet.webp",
    technologies: ["Next.js", "Tailwind CSS", "React"],
    link: "https://github.com/MisterAlvaro/Empet_LandingPage",
  },
  {
    id: 4,
    title: "NFT Marketplace",
    slug: "nft-marketplace",
    description: "Marketplace de NFTs desarrollado con JavaScript vanilla, demostrando dominio de fundamentos web.",
    image: "/images/nft.webp",
    technologies: ["HTML5", "CSS3", "JavaScript"],
    link: "https://github.com/MisterAlvaro/NFT_Store",
  },
  {
    id: 5,
    title: "Sistema de Gestión de Librería",
    slug: "libreria-backend",
    description: "API REST para la gestión completa de una librería, incluyendo préstamos y usuarios. Desarrollado con Spring Boot y siguiendo las mejores prácticas de arquitectura.",
    image: "/images/library.webp",
    technologies: ["Spring Boot", "Java", "PostgreSQL", "JPA"],
    link: "https://github.com/MisterAlvaro/Libreria_Backend",
  },
]
